name: notebook
channels:
  - conda-forge
dependencies:
  # TODO: turn into conda metapackage
  - bokeh=1.4
  - dask=2.11
  - dask-gateway=0.6
  - dask-kubernetes=0.10
  - dask-labextension=1.1
  - distributed=2.11
  - jupyterhub=1.1
  - jupyterlab=1.2
  - jupyter-server-proxy=1.2
  - nbgitpuller=0.8
  - python-graphviz=0.13
  - pip=20.0
  - tornado=6
