#!/bin/bash
set -euo pipefail

# labextensions
jupyter labextension install --clean dask-labextension \
                             @jupyter-widgets/jupyterlab-manager

DATE='2019-11-20'
VERSION="2.6.2_post"
NAME=StereoPipeline-$VERSION-$DATE-x86_64-Linux
wget -q https://byss.arc.nasa.gov/stereopipeline/daily_build/$NAME.tar.bz2
tar -xjf $NAME.tar.bz2
mv $NAME ${KERNEL_PYTHON_PREFIX}/StereoPipeline
rm $NAME.tar.bz2
